### ISSUE TITLE
First Time Setup

### ISSUE THREAD

**Issue by xvilo** [gled-rs/mastodon-autofollow#18]
Could you elaborate the install a bit more? 
I've cloned and install the dependencies. 
But i'm not getting it to work! 

`What is the username` The registered email address?
`What is the password` Thats easy. 
`What is your instance` Easy too! (in my case that would be `https://mastodon.org.uk `)
`What is your botname` Bot username? In my case `followbot` (see https://mastodon.org.uk/@followbot)

The error I get with these settings is:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mastodon/Mastodon.py", line 146, in log_in
    self.access_token = response['access_token']
KeyError: 'access_token'
Traceback (most recent call last):
  File "/home/mastodon/autofollow/Autofollow.py", line 30, in <module>
    to_file = '.pytooter_usercred.txt'
  File "/usr/local/lib/python2.7/dist-packages/mastodon/Mastodon.py", line 150, in log_in
    raise MastodonIllegalArgumentError('Invalid user name, password or scopes: %s' % e)
mastodon.Mastodon.MastodonIllegalArgumentError: Invalid user name, password or scopes: 'access_token'
```

Not sure what is happening in here!

**Comment by Fastidious** [comment]
@xvilo same as #11. I think @gled-rs is discouraging people from using this bot, as an active conversation is happening somewhere to try to solve the federation problems for single user instances.

**Comment by gled-rs** [comment]
as said in #11 by @Fastidious. Thanks for understanding.
